[server]
address = "127.0.0.1"
port = 3000
gs_domain = "http://localhost:9000"
page_size = 20

[auth0]
domain = "https://dev-tero.eu.auth0.com/"
audience = "https://api.tero.com"

[[integrations]]
subject = "auth0|123456"
name = "auth0"

[[integrations]]
subject = "session|123456"
name = "session"
