name: CI Pipeline

on: [push, pull_request]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # To access code from the repo

      - name: Install cargo crates
        run: cargo install cargo-audit cargo-deny cargo-chef

      # - name: Security check
      #   run: cargo audit

      - name: Dependency policy check
        run: cargo deny check

      - name: Clippy check
        run: cargo clippy

      - name: Unit tests
        run: cargo test

      - name: Build
        run: |
          cargo chef prepare --recipe-path recipe.json
          cargo chef cook --recipe-path recipe.json
          cargo build --release
